services:
  nginx:
    container_name: ${NGINX_CONTAINER_NAME:-bento-nginx}
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ${NGINX_IMAGE:-bento-nginx:latest}
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - bento-client
      - bento-blazor
    networks:
      - bento-network

    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M

  jenkins:
    container_name: ${JENKINS_CONTAINER_NAME:-jenkins}
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    image: ${JENKINS_IMAGE:-bento-jenkins:latest}
    ports:
      - "${JENKINS_PORT:-8080}:8080"
      - "${JENKINS_AGENT_PORT:-50000}:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - bento-network
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1G

volumes:
  jenkins_home:

networks:
  bento-network:
    name: ${BENTO_NETWORK_NAME:-bento-network}
