apiVersion: v1
kind: ConfigMap
metadata:
  name: bento-app-config
  namespace: bento
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ConnectionStrings__PostgreSql: "Host=postgres;Port=5432;Database=bentodb;Username=bento;Password=bento123"
  Redis__ConnectionString: "redis:6379,password=redis123"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__UserName: "guest"
  RabbitMq__Password: "guest"
  RabbitMq__QueueName: "order-created"
  Mongo__ConnectionString: "mongodb://bento:bento123@mongo:27017"
  Mongo__Database: "bento_logs"
  Mongo__OrderCollection: "order_logs"
  Cache__AdminApiKey: "replace-with-a-long-random-value"
  Cors__AllowedOrigins__0: "http://localhost:3000"
  Cors__AllowedOrigins__1: "http://localhost:3001"
  Cors__AllowedOrigins__2: "http://localhost"
  POSTGRES_USER: "bento"
  POSTGRES_PASSWORD: "bento123"
  POSTGRES_DB: "bentodb"
  MONGO_INITDB_ROOT_USERNAME: "bento"
  MONGO_INITDB_ROOT_PASSWORD: "bento123"
  REDIS_PASSWORD: "redis123"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
  Gateway__BaseUrl: "http://bento-gateway:5000/gateway"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bento-nginx-config
  namespace: bento
data:
  default.conf: |
    upstream bento_frontends {
      server bento-client:3000;
      server bento-blazor:3001;
    }

    server {
      listen 80;
      server_name _;

      location / {
        proxy_pass http://bento_frontends;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }
    }
