apiVersion: apps/v1
kind: Deployment
metadata:
  name: bento-client
  namespace: bento
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bento-client
  template:
    metadata:
      labels:
        app: bento-client
    spec:
      containers:
        - name: bento-client
          image: your-dockerhub-name/bento-client:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bento-client
  namespace: bento
spec:
  selector:
    app: bento-client
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
